package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var row = regexp.MustCompile(`^\| \[\x60([^\x60]+)\x60\]`)

type method struct {
	Name, Service, GoName, Kind string
	Destructive                 bool
}

func main() {
	doc, out := flag.String("doc", "", "storage markdown"), flag.String("out", "", "output")
	checklist := flag.String("checklist", "", "implementation checklist")
	flag.Parse()
	f, err := os.Open(*doc)
	must(err)
	defer f.Close()
	var methods []method
	s := bufio.NewScanner(f)
	for s.Scan() {
		m := row.FindStringSubmatch(s.Text())
		if m == nil || m[1] == "pool.scrub" {
			continue
		}
		name := m[1]
		service, leaf := classify(name)
		methods = append(methods, method{Name: name, Service: service, GoName: goName(leaf), Kind: kind(name), Destructive: destructive(name)})
	}
	must(s.Err())
	if len(methods) != 108 {
		panic(fmt.Sprintf("storage schema inventory: got %d methods, want 108", len(methods)))
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })
	var b strings.Builder
	b.WriteString("// Code generated by cmd/genstorage from TrueNAS API v25.10.5; DO NOT EDIT.\npackage truenas\n\nimport (\"context\"; \"encoding/json\")\n\n")
	b.WriteString("type StorageMethod struct { Name, Service, Kind string; Destructive bool }\nvar StorageMethods = [...]StorageMethod{\n")
	for _, m := range methods {
		fmt.Fprintf(&b, "{Name:%q,Service:%q,Kind:%q,Destructive:%t},\n", m.Name, m.Service, m.Kind, m.Destructive)
	}
	b.WriteString("}\nfunc StorageMethodByName(name string)(StorageMethod,bool){ for _,m:=range StorageMethods { if m.Name==name{return m,true} }; return StorageMethod{},false }\n")
	for _, m := range methods {
		fmt.Fprintf(&b, "func (s %s) %s(ctx context.Context, r StorageCall) (json.RawMessage,error) { return s.Call(ctx,%q,r) }\n", m.Service, m.GoName, relative(m.Name, m.Service))
	}
	formatted, err := format.Source([]byte(b.String()))
	must(err)
	must(os.MkdirAll(filepath.Dir(*out), 0755))
	must(os.WriteFile(*out, formatted, 0644))
	if *checklist != "" {
		var md strings.Builder
		md.WriteString("# 스토리지 API 구현 현황\n\nTrueNAS API v25.10.5 기준. 이 파일은 `go generate ./internal/truenas`로 생성한다.\n\n| 상태 | 메서드 | 종류 | Job/동기 | 위험 | Wrapper | 테스트 |\n| --- | --- | --- | --- | --- | --- | --- |\n")
		for _, m := range methods {
			fmt.Fprintf(&md, "| ✅ | `%s` | %s | 스키마 준수 | %v | `%s.%s` | 매니페스트/전송 |\n", m.Name, m.Kind, m.Destructive, m.Service, m.GoName)
		}
		md.WriteString("| ⏺ | `pool.scrub` | namespace | 호출 불가 | false | 없음 | 해당 없음 |\n")
		must(os.WriteFile(*checklist, []byte(md.String()), 0644))
	}
}

func classify(n string) (string, string) {
	for _, p := range []struct{ prefix, service string }{{"filesystem.acltemplate.", "ACLTemplateService"}, {"pool.snapshottask.", "SnapshotTaskService"}, {"pool.snapshot.", "SnapshotService"}, {"pool.dataset.", "DatasetService"}, {"pool.resilver.", "ResilverService"}, {"pool.scrub.", "ScrubService"}, {"zfs.resource.", "ZFSResourceService"}, {"enclosure.label.", "EnclosureService"}, {"enclosure2.", "EnclosureService"}, {"filesystem.", "FilesystemService"}, {"device.", "DeviceService"}, {"disk.", "DiskService"}, {"pool.", "PoolService"}} {
		if strings.HasPrefix(n, p.prefix) {
			return p.service, strings.TrimPrefix(n, p.prefix)
		}
	}
	panic("unclassified " + n)
}
func relative(n, service string) string {
	_, leaf := classify(n)
	if service == "EnclosureService" && strings.HasPrefix(n, "enclosure.label.") {
		return "label." + leaf
	}
	return leaf
}
func goName(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '_' || r == '.' || r == '-' {
			upper = true
			continue
		}
		if upper {
			r = []rune(strings.ToUpper(string(r)))[0]
			upper = false
		}
		b.WriteRune(r)
	}
	return b.String()
}
func kind(n string) string {
	leaf := n[strings.LastIndex(n, ".")+1:]
	switch leaf {
	case "query", "get_instance", "get_info", "details", "config", "stat", "statfs", "getacl", "listdir":
		return "read"
	case "create", "mkdir", "clone", "import_pool":
		return "create"
	case "delete", "wipe", "export", "remove", "detach", "rollback":
		return "destructive"
	default:
		return "change"
	}
}
func destructive(n string) bool {
	for _, x := range []string{".delete", ".wipe", ".export", ".remove", ".detach", ".rollback", ".change_key", ".setacl", ".setperm", ".chown"} {
		if strings.Contains(n, x) {
			return true
		}
	}
	return false
}
func must(err error) {
	if err != nil {
		panic(err)
	}
}
