<script lang="ts">
    import { onMount } from 'svelte';
    import { Camera, KeyRound, Lock, Pencil, Plus, Trash2, Unlock } from '@lucide/svelte';
    import * as Alert from '$lib/components/ui/alert'; import { Badge } from '$lib/components/ui/badge'; import { Button } from '$lib/components/ui/button'; import { Checkbox } from '$lib/components/ui/checkbox'; import * as Card from '$lib/components/ui/card'; import * as Dialog from '$lib/components/ui/dialog'; import { Input } from '$lib/components/ui/input'; import { Label } from '$lib/components/ui/label'; import * as NativeSelect from '$lib/components/ui/native-select'; import { Spinner } from '$lib/components/ui/spinner'; import * as Table from '$lib/components/ui/table'; import { Textarea } from '$lib/components/ui/textarea';
    import type { DatasetMutation, StorageDataset } from '../../../bindings/github.com/ironpark/toolz/desktop/charmtrue';
    import { getAppContext } from './context.svelte'; import { formatBytes } from './format';

    const GiB=1024**3, app=getAppContext();
    let query=$state(''), busy=$state('');
    let editorOpen=$state(false), snapshotOpen=$state(false), unlockOpen=$state(false), deleteOpen=$state(false);
    let deleteTarget=$state<StorageDataset|null>(null), recursiveDelete=$state(false), forceDelete=$state(false);
    let snapshotDataset=$state(''), snapshotName=$state('manual'), snapshotRecursive=$state(false);
    let unlockDataset=$state(''), unlockSecret=$state(''), unlockRecursive=$state(false), unlockForce=$state(false);
    const pools=$derived(app.storage?.pools??[]);
    let form=$state<DatasetMutation>(emptyForm());
    onMount(()=>{if(!app.storage)void app.refreshStorage()});
    const datasets=$derived((app.storage?.datasets??[]).filter(d=>!query||`${d.name} ${d.mountpoint} ${d.comments}`.toLowerCase().includes(query.toLowerCase())));
    function emptyForm():DatasetMutation{return{id:'',name:pools[0]?`${pools[0].name}/`:'',type:'FILESYSTEM',comments:'',compression:'INHERIT',sync:'INHERIT',atime:'INHERIT',readonly:'INHERIT',recordsize:'',quota:0,refquota:0,volsize:0,volblocksize:'16K',sparse:false,shareType:'GENERIC',createAncestors:false,forceRename:false}}
    function createDataset(){form=emptyForm();editorOpen=true}
    function editDataset(d:StorageDataset){form={id:d.id,name:d.id,type:d.type,comments:d.comments,compression:d.compression||'INHERIT',sync:d.sync||'INHERIT',atime:d.atime||'INHERIT',readonly:d.readonly||'INHERIT',recordsize:d.recordsize,quota:d.quota,refquota:d.refquota,volsize:d.volsize,volblocksize:'',sparse:false,shareType:'GENERIC',createAncestors:false,forceRename:false};editorOpen=true}
    async function save(e:SubmitEvent){e.preventDefault();busy='save';try{await app.saveDataset(form);editorOpen=false}finally{busy=''}}
    function askDelete(d:StorageDataset){deleteTarget=d;recursiveDelete=false;forceDelete=false;deleteOpen=true}
    async function remove(){if(!deleteTarget)return;busy='delete';try{await app.deleteDataset({id:deleteTarget.id,recursive:recursiveDelete,force:forceDelete});deleteOpen=false}finally{busy=''}}
    function openSnapshot(d:StorageDataset){snapshotDataset=d.id;snapshotName=`manual-${new Date().toISOString().slice(0,10)}`;snapshotRecursive=false;snapshotOpen=true}
    async function createSnapshot(e:SubmitEvent){e.preventDefault();busy='snapshot';try{await app.createDatasetSnapshot({dataset:snapshotDataset,name:snapshotName,recursive:snapshotRecursive});snapshotOpen=false}finally{busy=''}}
    function openUnlock(d:StorageDataset){unlockDataset=d.id;unlockSecret='';unlockRecursive=false;unlockForce=false;unlockOpen=true}
    async function unlock(e:SubmitEvent){e.preventDefault();busy='unlock';try{await app.setDatasetLocked(unlockDataset,unlockSecret,false,unlockRecursive,unlockForce);unlockOpen=false}finally{busy=''}}
    async function lock(d:StorageDataset){busy=`lock-${d.id}`;try{await app.setDatasetLocked(d.id,'',true,false,false)}finally{busy=''}}
    const bytesToGiB=(v:number)=>v?v/GiB:0;
    const setGiB=(key:'quota'|'refquota'|'volsize',value:string)=>{form[key]=Math.max(0,Number(value)||0)*GiB};
</script>

<section class="space-y-6">
    {#if app.storageError}<Alert.Root variant="destructive"><Alert.Title>데이터셋 작업 실패</Alert.Title><Alert.Description>{app.storageError}</Alert.Description></Alert.Root>{/if}
    <Card.Root><Card.Header class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><Card.Title>데이터셋 목록</Card.Title><Card.Description>{app.storage?.datasets?.length??0}개 데이터셋 · {app.storage?.snapshotCount??0}개 스냅샷</Card.Description></div><div class="flex gap-2"><Input class="min-w-56" bind:value={query} placeholder="이름, 경로, 설명 검색"/><Button onclick={createDataset}><Plus/>추가</Button></div></Card.Header><Card.Content>
        {#if app.storageLoading&&!app.storage}<div class="grid min-h-48 place-items-center"><Spinner aria-label="데이터셋 불러오는 중"/></div>
        {:else if datasets.length}<Table.Root><Table.Header><Table.Row><Table.Head>데이터셋</Table.Head><Table.Head>유형</Table.Head><Table.Head>사용량</Table.Head><Table.Head>가용</Table.Head><Table.Head>보안</Table.Head><Table.Head class="w-40 text-right">작업</Table.Head></Table.Row></Table.Header><Table.Body>{#each datasets as d(d.id)}<Table.Row><Table.Cell><p class="font-medium">{d.name}</p><p class="text-xs text-muted-foreground">{d.comments||d.mountpoint||d.id}</p></Table.Cell><Table.Cell><Badge variant="outline">{d.type==='VOLUME'?'zvol':'파일시스템'}</Badge></Table.Cell><Table.Cell>{formatBytes(d.used)}</Table.Cell><Table.Cell>{formatBytes(d.available)}</Table.Cell><Table.Cell><Badge variant={d.locked?'destructive':'secondary'}>{d.locked?'잠김':d.encrypted?'암호화':d.readonly==='ON'?'읽기 전용':'일반'}</Badge></Table.Cell><Table.Cell><div class="flex justify-end gap-1"><Button variant="ghost" size="icon-sm" title="스냅샷" aria-label={`${d.name} 스냅샷 생성`} onclick={()=>openSnapshot(d)}><Camera/></Button>{#if d.encrypted}{#if d.locked}<Button variant="ghost" size="icon-sm" title="잠금 해제" aria-label={`${d.name} 잠금 해제`} onclick={()=>openUnlock(d)}><Unlock/></Button>{:else}<Button variant="ghost" size="icon-sm" title="잠금" aria-label={`${d.name} 잠금`} disabled={busy===`lock-${d.id}`} onclick={()=>lock(d)}><Lock/></Button>{/if}{/if}<Button variant="ghost" size="icon-sm" title="수정" aria-label={`${d.name} 수정`} disabled={d.locked} onclick={()=>editDataset(d)}><Pencil/></Button><Button variant="ghost" size="icon-sm" class="text-destructive hover:bg-destructive/10 hover:text-destructive" title="삭제" aria-label={`${d.name} 삭제`} disabled={!d.id.includes('/')} onclick={()=>askDelete(d)}><Trash2/></Button></div></Table.Cell></Table.Row>{/each}</Table.Body></Table.Root>
        {:else}<p class="py-12 text-center text-sm text-muted-foreground">{query?'검색 결과가 없습니다.':'표시할 데이터셋이 없습니다.'}</p>{/if}
    </Card.Content></Card.Root>
</section>

<Dialog.Root bind:open={editorOpen}><Dialog.Content class="max-h-[88dvh] overflow-y-auto sm:max-w-2xl"><form class="space-y-5" onsubmit={save}><Dialog.Header><Dialog.Title>{form.id?'데이터셋 수정':'데이터셋 추가'}</Dialog.Title><Dialog.Description>풀을 포함한 전체 경로와 ZFS 속성을 설정합니다.</Dialog.Description></Dialog.Header><div class="grid gap-4 sm:grid-cols-2">
    <div class="grid gap-2 sm:col-span-2"><Label for="dataset-name">전체 이름</Label><Input id="dataset-name" bind:value={form.name} placeholder="tank/data" required/></div>
    {#if !form.id}<div class="grid gap-2"><Label>유형</Label><NativeSelect.Root bind:value={form.type}><option value="FILESYSTEM">파일시스템</option><option value="VOLUME">zvol</option></NativeSelect.Root></div><div class="grid gap-2"><Label>용도</Label><NativeSelect.Root bind:value={form.shareType}><option value="GENERIC">일반</option><option value="SMB">SMB</option><option value="NFS">NFS</option><option value="MULTIPROTOCOL">SMB + NFS</option><option value="APPS">앱</option></NativeSelect.Root></div>{/if}
    <div class="grid gap-2 sm:col-span-2"><Label>설명</Label><Textarea bind:value={form.comments}/></div>
    <div class="grid gap-2"><Label>압축</Label><NativeSelect.Root bind:value={form.compression}><option value="INHERIT">상속</option><option value="LZ4">LZ4</option><option value="ZSTD">ZSTD</option><option value="GZIP">GZIP</option><option value="OFF">사용 안 함</option></NativeSelect.Root></div>
    <div class="grid gap-2"><Label>동기 쓰기</Label><NativeSelect.Root bind:value={form.sync}><option value="INHERIT">상속</option><option value="STANDARD">표준</option><option value="ALWAYS">항상</option><option value="DISABLED">사용 안 함</option></NativeSelect.Root></div>
    <div class="grid gap-2"><Label>읽기 전용</Label><NativeSelect.Root bind:value={form.readonly}><option value="INHERIT">상속</option><option value="OFF">끔</option><option value="ON">켬</option></NativeSelect.Root></div>
    {#if form.type==='FILESYSTEM'}<div class="grid gap-2"><Label>접근 시간 기록</Label><NativeSelect.Root bind:value={form.atime}><option value="INHERIT">상속</option><option value="OFF">끔</option><option value="ON">켬</option></NativeSelect.Root></div><div class="grid gap-2"><Label>전체 할당량 (GiB)</Label><Input type="number" min="0" step="1" value={bytesToGiB(form.quota)} oninput={e=>setGiB('quota',e.currentTarget.value)}/></div><div class="grid gap-2"><Label>데이터셋 할당량 (GiB)</Label><Input type="number" min="0" step="1" value={bytesToGiB(form.refquota)} oninput={e=>setGiB('refquota',e.currentTarget.value)}/></div><div class="grid gap-2"><Label>레코드 크기</Label><NativeSelect.Root bind:value={form.recordsize}><option value="">기본값</option><option value="16K">16 KiB</option><option value="128K">128 KiB</option><option value="1M">1 MiB</option></NativeSelect.Root></div>
    {:else}<div class="grid gap-2"><Label>zvol 용량 (GiB)</Label><Input type="number" min="1" step="1" value={bytesToGiB(form.volsize)} oninput={e=>setGiB('volsize',e.currentTarget.value)} required/></div>{#if !form.id}<div class="grid gap-2"><Label>블록 크기</Label><NativeSelect.Root bind:value={form.volblocksize}><option value="8K">8 KiB</option><option value="16K">16 KiB</option><option value="32K">32 KiB</option><option value="64K">64 KiB</option><option value="128K">128 KiB</option></NativeSelect.Root></div>{/if}{/if}
    </div>{#if !form.id}<label class="flex items-center gap-2 text-sm"><Checkbox bind:checked={form.createAncestors}/>누락된 상위 데이터셋도 생성</label>{#if form.type==='VOLUME'}<label class="flex items-center gap-2 text-sm"><Checkbox bind:checked={form.sparse}/>씬 프로비저닝 사용</label>{/if}{:else if form.name!==form.id}<Alert.Root><Alert.Title>이름 변경 주의</Alert.Title><Alert.Description>공유, 스냅샷 작업 및 복제 연결이 중단될 수 있습니다.</Alert.Description></Alert.Root><label class="flex items-center gap-2 text-sm"><Checkbox bind:checked={form.forceRename}/>영향을 이해했으며 강제로 이름 변경</label>{/if}<Dialog.Footer><Button type="button" variant="outline" onclick={()=>editorOpen=false}>취소</Button><Button type="submit" disabled={busy==='save'}>{#if busy==='save'}<Spinner/>{/if}저장</Button></Dialog.Footer></form></Dialog.Content></Dialog.Root>

<Dialog.Root bind:open={snapshotOpen}><Dialog.Content><form class="space-y-5" onsubmit={createSnapshot}><Dialog.Header><Dialog.Title>스냅샷 생성</Dialog.Title><Dialog.Description>{snapshotDataset}의 현재 상태를 보존합니다.</Dialog.Description></Dialog.Header><div class="grid gap-2"><Label for="snapshot-name">스냅샷 이름</Label><Input id="snapshot-name" bind:value={snapshotName} required/></div><label class="flex items-center gap-2 text-sm"><Checkbox bind:checked={snapshotRecursive}/>하위 데이터셋 포함</label><Dialog.Footer><Button type="button" variant="outline" onclick={()=>snapshotOpen=false}>취소</Button><Button type="submit" disabled={busy==='snapshot'}>{#if busy==='snapshot'}<Spinner/>{:else}<Camera/>{/if}생성</Button></Dialog.Footer></form></Dialog.Content></Dialog.Root>

<Dialog.Root bind:open={unlockOpen}><Dialog.Content><form class="space-y-5" onsubmit={unlock}><Dialog.Header><Dialog.Title>데이터셋 잠금 해제</Dialog.Title><Dialog.Description>{unlockDataset}의 암호 또는 64자리 암호화 키를 입력하세요.</Dialog.Description></Dialog.Header><div class="grid gap-2"><Label for="unlock-secret">암호화 키 또는 암호</Label><Input id="unlock-secret" type="password" bind:value={unlockSecret} autocomplete="off" required/></div><label class="flex items-center gap-2 text-sm"><Checkbox bind:checked={unlockRecursive}/>암호화된 하위 데이터셋 포함</label><label class="flex items-center gap-2 text-sm"><Checkbox bind:checked={unlockForce}/>마운트 경로 충돌 시 강제 처리</label><Dialog.Footer><Button type="button" variant="outline" onclick={()=>unlockOpen=false}>취소</Button><Button type="submit" disabled={busy==='unlock'}>{#if busy==='unlock'}<Spinner/>{:else}<KeyRound/>{/if}잠금 해제</Button></Dialog.Footer></form></Dialog.Content></Dialog.Root>

<Dialog.Root bind:open={deleteOpen}><Dialog.Content><Dialog.Header><Dialog.Title>“{deleteTarget?.name??''}” 데이터셋을 삭제할까요?</Dialog.Title><Dialog.Description>데이터가 영구 삭제되며 되돌릴 수 없습니다.</Dialog.Description></Dialog.Header><div class="grid gap-3"><label class="flex items-center gap-2 text-sm"><Checkbox bind:checked={recursiveDelete}/>하위 데이터셋과 스냅샷도 재귀적으로 삭제</label><label class="flex items-center gap-2 text-sm"><Checkbox bind:checked={forceDelete}/>사용 중이어도 강제 삭제</label></div><Dialog.Footer><Button variant="outline" onclick={()=>deleteOpen=false}>취소</Button><Button variant="destructive" disabled={busy==='delete'} onclick={remove}>{#if busy==='delete'}<Spinner/>{/if}영구 삭제</Button></Dialog.Footer></Dialog.Content></Dialog.Root>
