<script lang="ts">
    import { onMount } from 'svelte'; import { RefreshCw } from '@lucide/svelte';
    import * as Alert from '$lib/components/ui/alert'; import { Badge } from '$lib/components/ui/badge'; import { Button } from '$lib/components/ui/button'; import * as Card from '$lib/components/ui/card'; import { Progress } from '$lib/components/ui/progress'; import * as Table from '$lib/components/ui/table';
    import { getAppContext } from './context.svelte'; import { formatBytes } from './format';
    const app = getAppContext(); onMount(() => { if (!app.storage) void app.refreshStorage(); });
    const pools = $derived(app.storage?.pools ?? []); const disks = $derived(app.storage?.disks ?? []); const total = $derived(app.storage?.totalSize ?? 0); const used = $derived(app.storage?.totalAllocated ?? 0);
</script>
<section class="space-y-6"><header class="flex items-end justify-between"><div><h2 class="text-3xl font-semibold tracking-tight">스토리지 풀</h2><p class="mt-1 text-sm text-muted-foreground">풀 용량과 상태, 연결된 디스크를 확인합니다.</p></div><Button variant="outline" disabled={app.storageLoading} onclick={() => app.refreshStorage()}><RefreshCw class={app.storageLoading?'animate-spin':''}/>새로고침</Button></header>
{#if app.storageError}<Alert.Root variant="destructive"><Alert.Title>스토리지 조회 실패</Alert.Title><Alert.Description>{app.storageError}</Alert.Description></Alert.Root>{/if}
<div class="grid gap-4 md:grid-cols-3"><Card.Root><Card.Header><Card.Description>전체 용량</Card.Description><Card.Title class="text-2xl">{formatBytes(total)}</Card.Title></Card.Header></Card.Root><Card.Root><Card.Header><Card.Description>사용 중</Card.Description><Card.Title class="text-2xl">{formatBytes(used)}</Card.Title></Card.Header><Card.Content><Progress value={total?used/total*100:0}/></Card.Content></Card.Root><Card.Root><Card.Header><Card.Description>디스크</Card.Description><Card.Title class="text-2xl">{disks.length}개</Card.Title></Card.Header></Card.Root></div>
<div class="grid gap-4 xl:grid-cols-2"><Card.Root><Card.Header><Card.Title>풀 목록</Card.Title><Card.Description>{pools.length}개 풀</Card.Description></Card.Header><Card.Content>{#if !app.storageLoading&&pools.length===0}<p class="py-10 text-center text-sm text-muted-foreground">표시할 풀이 없습니다.</p>{:else}<Table.Root><Table.Header><Table.Row><Table.Head>이름</Table.Head><Table.Head>상태</Table.Head><Table.Head>사용량</Table.Head><Table.Head class="text-right">용량</Table.Head></Table.Row></Table.Header><Table.Body>{#each pools as pool}<Table.Row><Table.Cell class="font-medium">{pool.name}</Table.Cell><Table.Cell><Badge variant={pool.healthy?'secondary':'destructive'}>{pool.status}</Badge></Table.Cell><Table.Cell>{pool.size?Math.round(pool.allocated/pool.size*100):0}%</Table.Cell><Table.Cell class="text-right">{formatBytes(pool.size)}</Table.Cell></Table.Row>{/each}</Table.Body></Table.Root>{/if}</Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>물리 디스크</Card.Title><Card.Description>{disks.length}개 장치</Card.Description></Card.Header><Card.Content class="divide-y">{#if !app.storageLoading&&disks.length===0}<p class="py-10 text-center text-sm text-muted-foreground">감지된 디스크가 없습니다.</p>{:else}{#each disks as disk}<div class="flex items-center justify-between gap-4 py-3"><div class="min-w-0"><p class="truncate text-sm font-medium">{disk.name||disk.identifier}</p><p class="truncate text-xs text-muted-foreground">{disk.model||'모델 정보 없음'} · {disk.serial||'시리얼 없음'}</p></div><div class="text-right"><p class="text-sm font-medium">{formatBytes(disk.size)}</p><p class="text-xs text-muted-foreground">{disk.pool||disk.type||'미할당'}</p></div></div>{/each}{/if}</Card.Content></Card.Root></div></section>
