// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TrueNASService from "./truenasservice.js";
export {
    TrueNASService
};

export type {
    AppInfo
} from "./models.js";
