// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TrueNASService from "./truenasservice.js";
export {
    TrueNASService
};

export type {
    APIKeyInfo,
    APIKeyMutation,
    APIKeyMutationResult,
    AppInfo,
    ConnectionInfo,
    DatasetDeleteOptions,
    DatasetMutation,
    DatasetSnapshotMutation,
    GroupInfo,
    GroupMutation,
    IdentityOverview,
    NetworkAliasInfo,
    NetworkAliasMutation,
    NetworkConfiguration,
    NetworkConfigurationMutation,
    NetworkInterfaceInfo,
    NetworkInterfaceMutation,
    NetworkOverview,
    NetworkSummary,
    NetworkSummaryIPInfo,
    RsyncTaskInfo,
    RsyncTaskMutation,
    SMBShareACL,
    SMBShareACLEntry,
    SavedServer,
    ShareInfo,
    ShareMutation,
    SharingOverview,
    StaticRouteInfo,
    StaticRouteMutation,
    StorageDataset,
    StorageDisk,
    StorageOverview,
    StoragePool,
    SystemInfo,
    SystemManagementOverview,
    SystemServiceInfo,
    UpdateInfo,
    UserInfo,
    UserMutation,
    UserMutationResult
} from "./models.js";
