// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ACLTemplateInfo {
    "id": number;
    "name": string;
    "comment": string;
    "builtin": boolean;
    "aclType": string;
    "entries": FilesystemACLEntry[] | null;
}

export interface APIKeyInfo {
    "id": number;
    "name": string;
    "username": string;
    "revoked": boolean;
    "expiresAt": string;
}

export interface APIKeyMutation {
    "id": number;
    "name": string;
    "username": string;
    "expiresAt": string;
    "reset": boolean;
}

export interface APIKeyMutationResult {
    "id": number;
    "key": string;
}

export interface AppInfo {
    "name": string;
    "version": string;
    "status": string;
}

/**
 * CertificateInfo is a frontend-friendly summary of a TrueNAS certificate.
 */
export interface CertificateInfo {
    "id": number;
    "name": string;
    "commonName": string;
    "subjectAltNames": string[] | null;
    "issuer": string;
    "from": string;
    "until": string;
    "type": string;
    "expired": boolean;
    "hasPrivateKey": boolean;
    "uiActive": boolean;
}

/**
 * CertificateInstall imports a certificate and optionally binds it to the UI.
 */
export interface CertificateInstall {
    "name": string;
    "certificate": string;
    "privateKey": string;
    "applyToUi": boolean;
}

/**
 * CertificateOverview lists certificates plus the one bound to the web UI.
 */
export interface CertificateOverview {
    "certificates": CertificateInfo[] | null;
    "uiCertificateId": number;
}

/**
 * ConnectionInfo describes the currently connected TrueNAS system.
 */
export interface ConnectionInfo {
    "connected": boolean;
    "endpoint": string;
    "system": SystemInfo;
}

export interface DatasetDeleteOptions {
    "id": string;
    "recursive": boolean;
    "force": boolean;
}

/**
 * DatasetMutation contains the commonly managed pool.dataset properties.
 * Sizes are expressed in bytes; zero clears an optional quota.
 */
export interface DatasetMutation {
    "id": string;
    "name": string;
    "type": string;
    "comments": string;
    "compression": string;
    "sync": string;
    "atime": string;
    "readonly": string;
    "recordsize": string;
    "quota": number;
    "refquota": number;
    "volsize": number;
    "volblocksize": string;
    "sparse": boolean;
    "shareType": string;
    "createAncestors": boolean;
    "forceRename": boolean;
}

export interface DatasetSnapshotMutation {
    "dataset": string;
    "name": string;
    "recursive": boolean;
}

/**
 * FilesystemACL is the UI-safe representation shared by NFSv4 and POSIX1e
 * filesystem ACLs. Basic and advanced permission/flag forms are kept separate
 * so loading and saving an ACL does not discard fields the editor did not alter.
 */
export interface FilesystemACL {
    "path": string;
    "user": string;
    "group": string;
    "uid": number;
    "gid": number;
    "aclType": string;
    "trivial": boolean;
    "entries": FilesystemACLEntry[] | null;
    "nfs41Flags": { [_ in string]?: boolean } | null;
}

export interface FilesystemACLEntry {
    "tag": string;
    "type": string;
    "id": number;
    "hasId": boolean;
    "who": string;
    "basicPerms": string;
    "permissions": { [_ in string]?: boolean } | null;
    "basicFlags": string;
    "flags": { [_ in string]?: boolean } | null;
    "default": boolean;
}

export interface FilesystemACLMutation {
    "path": string;
    "aclType": string;
    "user": string;
    "group": string;
    "entries": FilesystemACLEntry[] | null;
    "nfs41Flags": { [_ in string]?: boolean } | null;
    "stripAcl": boolean;
    "recursive": boolean;
    "traverse": boolean;
    "canonicalize": boolean;
    "validateEffectiveAcl": boolean;
}

/**
 * GeneratedCertificate holds PEM output equivalent to `openssl req -x509`.
 */
export interface GeneratedCertificate {
    "name": string;
    "certificate": string;
    "privateKey": string;
    "opensslConfig": string;
    "notAfter": string;
    "fingerprint": string;
}

export interface GroupInfo {
    "id": number;
    "gid": number;
    "name": string;
    "local": boolean;
    "builtin": boolean;
    "userCount": number;
    "smb": boolean;
}

export interface GroupMutation {
    "id": number;
    "name": string;
    "smb": boolean;
}

export interface IdentityOverview {
    "users": UserInfo[] | null;
    "groups": GroupInfo[] | null;
    "apiKeys": APIKeyInfo[] | null;
    "shellChoices": { [_ in string]?: string } | null;
}

export interface InterfaceTraffic {
    "name": string;
    "receivedKbps": number | null;
    "sentKbps": number | null;
    "sampledAt": number;
}

export interface NetworkAliasInfo {
    "type": string;
    "address": string;
    "netmask": number;
}

export interface NetworkAliasMutation {
    "type": string;
    "address": string;
    "netmask": number;
}

export interface NetworkConfiguration {
    "hostname": string;
    "domain": string;
    "ipv4Gateway": string;
    "ipv6Gateway": string;
    "nameServers": string[] | null;
    "httpProxy": string;
    "hosts": string[] | null;
    "searchDomains": string[] | null;
    "announceNetbios": boolean;
    "announceMdns": boolean;
    "announceWsd": boolean;
}

export interface NetworkConfigurationMutation {
    "hostname": string;
    "domain": string;
    "ipv4Gateway": string;
    "ipv6Gateway": string;
    "nameServers": string[] | null;
    "httpProxy": string;
    "hosts": string[] | null;
    "searchDomains": string[] | null;
    "announceNetbios": boolean;
    "announceMdns": boolean;
    "announceWsd": boolean;
}

export interface NetworkInterfaceInfo {
    "id": string;
    "name": string;
    "type": string;
    "description": string;
    "linkState": string;
    "mediaType": string;
    "mediaSubtype": string;
    "macAddress": string;
    "mtu": number;
    "ipv4Dhcp": boolean;
    "ipv6Auto": boolean;
    "aliases": NetworkAliasInfo[] | null;
    "lagProtocol": string;
    "lagPorts": string[] | null;
    "bridgeMembers": string[] | null;
    "vlanParent": string;
    "vlanTag": number;
    "vlanPriority": number;
    "enableLearning": boolean;
}

export interface NetworkInterfaceMutation {
    "id": string;
    "name": string;
    "type": string;
    "description": string;
    "ipv4Dhcp": boolean;
    "ipv6Auto": boolean;
    "aliases": NetworkAliasMutation[] | null;
    "mtu": number;
    "lagProtocol": string;
    "lagPorts": string[] | null;
    "bridgeMembers": string[] | null;
    "vlanParent": string;
    "vlanTag": number;
    "vlanPriority": number;
    "enableLearning": boolean;
}

export interface NetworkOverview {
    "interfaces": NetworkInterfaceInfo[] | null;
    "configuration": NetworkConfiguration;
    "summary": NetworkSummary;
    "staticRoutes": StaticRouteInfo[] | null;
    "pendingChanges": boolean;
    "checkinRemaining": number;
}

export interface NetworkSummary {
    "ips": { [_ in string]?: NetworkSummaryIPInfo } | null;
    "defaultRoutes": string[] | null;
    "nameServers": string[] | null;
}

export interface NetworkSummaryIPInfo {
    "ipv4": string[] | null;
    "ipv6": string[] | null;
}

export interface OverviewLiveStats {
    "uptimeSeconds": number | null;
    "uptimeSampledAt": number;
    "uptimeError": string;
    "traffic": InterfaceTraffic[] | null;
    "trafficError": string;
    "network": NetworkSummary;
    "networkError": string;
}

export interface RsyncTaskInfo {
    "id": number;
    "path": string;
    "user": string;
    "mode": string;
    "remoteHost": string;
    "remotePort": number;
    "remoteModule": string;
    "remotePath": string;
    "sshCredentialId": number;
    "destination": string;
    "direction": string;
    "description": string;
    "scheduleMinute": string;
    "scheduleHour": string;
    "scheduleDayOfMonth": string;
    "scheduleMonth": string;
    "scheduleDayOfWeek": string;
    "recursive": boolean;
    "times": boolean;
    "compress": boolean;
    "archive": boolean;
    "delete": boolean;
    "quiet": boolean;
    "preservePermissions": boolean;
    "preserveAttributes": boolean;
    "delayUpdates": boolean;
    "extra": string[] | null;
    "enabled": boolean;
    "validateRemotePath": boolean;
    "sshKeyScan": boolean;
    "locked": boolean;
}

export interface RsyncTaskMutation {
    "id": number;
    "path": string;
    "user": string;
    "mode": string;
    "remoteHost": string;
    "remotePort": number;
    "remoteModule": string;
    "remotePath": string;
    "sshCredentialId": number;
    "direction": string;
    "description": string;
    "scheduleMinute": string;
    "scheduleHour": string;
    "scheduleDayOfMonth": string;
    "scheduleMonth": string;
    "scheduleDayOfWeek": string;
    "recursive": boolean;
    "times": boolean;
    "compress": boolean;
    "archive": boolean;
    "delete": boolean;
    "quiet": boolean;
    "preservePermissions": boolean;
    "preserveAttributes": boolean;
    "delayUpdates": boolean;
    "extra": string[] | null;
    "enabled": boolean;
    "validateRemotePath": boolean;
    "sshKeyScan": boolean;
}

export interface SMBShareACL {
    "shareName": string;
    "entries": SMBShareACLEntry[] | null;
}

export interface SMBShareACLEntry {
    "permission": string;
    "entryType": string;
    "sid": string;
    "idType": string;
    "id": number;
    "hasId": boolean;
    "name": string;
}

/**
 * SavedServer is a reusable TrueNAS connection profile. Credentials are
 * deliberately excluded so passwords and API keys are never written to disk.
 */
export interface SavedServer {
    "id": string;
    "name": string;
    "endpoint": string;
    "username": string;
    "authenticationMethod": string;
    "allowPrivateCertificate": boolean;
    "credentialStored": boolean;
    "lastConnected": string;
}

/**
 * SelfSignedCertificateRequest mirrors the fields of an OpenSSL san.cnf.
 */
export interface SelfSignedCertificateRequest {
    "name": string;
    "commonName": string;
    "country": string;
    "state": string;
    "locality": string;
    "organization": string;
    "organizationalUnit": string;
    "ipAddresses": string[] | null;
    "dnsNames": string[] | null;
    "days": number;
    "keyBits": number;
}

export interface SetupPreset {
    "id": string;
    "name": string;
    "groups": string[] | null;
    "users": SetupPresetUser[] | null;
    "enableSSH": boolean;
    "adminUser": string;
    "replaceAdminUser": string;
}

export interface SetupPresetApply {
    "preset": SetupPreset;
    "expectedEndpoint": string;
    "passwords": { [_ in string]?: string } | null;
    "adminPassword": string;
    "replacementPassword": string;
}

export interface SetupPresetResult {
    "steps": SetupPresetStep[] | null;
    "complete": boolean;
}

export interface SetupPresetStep {
    "name": string;
    "status": string;
    "message": string;
}

export interface SetupPresetUser {
    "name": string;
    "fullName": string;
    "group": string;
    "smb": boolean;
}

export interface ShareInfo {
    "id": number;
    "protocol": string;
    "name": string;
    "path": string;
    "purpose": string;
    "comment": string;
    "enabled": boolean;
    "readOnly": boolean;
    "locked": boolean;
    "browsable": boolean;
    "accessBasedShareEnumeration": boolean;
    "auditEnabled": boolean;
    "auditWatchList": string[] | null;
    "auditIgnoreList": string[] | null;
    "recycleBin": boolean;
    "pathSuffix": string;
    "hostsAllow": string[] | null;
    "hostsDeny": string[] | null;
    "guestOk": boolean;
    "streams": boolean;
    "durableHandle": boolean;
    "shadowCopy": boolean;
    "fsrvp": boolean;
    "home": boolean;
    "acl": boolean;
    "afp": boolean;
    "timeMachine": boolean;
    "timeMachineQuota": number;
    "aaplNameMangling": boolean;
    "vuid": string;
    "auxSmbConf": string;
    "autoSnapshot": boolean;
    "autoDatasetCreation": boolean;
    "datasetNamingSchema": string;
    "gracePeriod": number;
    "autoQuota": number;
    "remotePath": string[] | null;
    "networks": string[] | null;
    "aliases": string[] | null;
    "hosts": string[] | null;
    "mapRootUser": string;
    "mapRootGroup": string;
    "mapAllUser": string;
    "mapAllGroup": string;
    "security": string[] | null;
    "exposeSnapshots": boolean;
}

export interface ShareMutation {
    "id": number;
    "protocol": string;
    "name": string;
    "path": string;
    "purpose": string;
    "comment": string;
    "enabled": boolean;
    "readOnly": boolean;
    "browsable": boolean;
    "accessBasedShareEnumeration": boolean;
    "auditEnabled": boolean;
    "auditWatchList": string[] | null;
    "auditIgnoreList": string[] | null;
    "recycleBin": boolean;
    "pathSuffix": string;
    "hostsAllow": string[] | null;
    "hostsDeny": string[] | null;
    "guestOk": boolean;
    "streams": boolean;
    "durableHandle": boolean;
    "shadowCopy": boolean;
    "fsrvp": boolean;
    "home": boolean;
    "acl": boolean;
    "afp": boolean;
    "timeMachine": boolean;
    "timeMachineQuota": number;
    "aaplNameMangling": boolean;
    "vuid": string;
    "auxSmbConf": string;
    "autoSnapshot": boolean;
    "autoDatasetCreation": boolean;
    "datasetNamingSchema": string;
    "gracePeriod": number;
    "autoQuota": number;
    "remotePath": string[] | null;
    "networks": string[] | null;
    "aliases": string[] | null;
    "hosts": string[] | null;
    "mapRootUser": string;
    "mapRootGroup": string;
    "mapAllUser": string;
    "mapAllGroup": string;
    "security": string[] | null;
    "exposeSnapshots": boolean;
}

export interface SharingOverview {
    "shares": ShareInfo[] | null;
    "rsyncTasks": RsyncTaskInfo[] | null;
    "smbCount": number;
    "nfsCount": number;
}

export interface StaticRouteInfo {
    "id": number;
    "destination": string;
    "gateway": string;
    "description": string;
}

export interface StaticRouteMutation {
    "id": number;
    "destination": string;
    "gateway": string;
    "description": string;
}

export interface StorageDataset {
    "id": string;
    "name": string;
    "pool": string;
    "type": string;
    "mountpoint": string;
    "encrypted": boolean;
    "locked": boolean;
    "used": number;
    "available": number;
    "comments": string;
    "compression": string;
    "sync": string;
    "atime": string;
    "readonly": string;
    "recordsize": string;
    "quota": number;
    "refquota": number;
    "volsize": number;
}

export interface StorageDisk {
    "name": string;
    "identifier": string;
    "model": string;
    "serial": string;
    "type": string;
    "size": number;
    "pool": string;
}

/**
 * StorageOverview is the frontend-facing snapshot of pools, disks, datasets,
 * and snapshots used by the storage management screens.
 */
export interface StorageOverview {
    "pools": StoragePool[] | null;
    "disks": StorageDisk[] | null;
    "datasets": StorageDataset[] | null;
    "snapshotCount": number;
    "totalSize": number;
    "totalAllocated": number;
    "totalFree": number;
}

export interface StoragePool {
    "id": number;
    "name": string;
    "guid": string;
    "status": string;
    "healthy": boolean;
    "size": number;
    "allocated": number;
    "free": number;
}

/**
 * SystemInfo contains the system.info fields needed by the initial UI.
 */
export interface SystemInfo {
    "hostname": string;
    "version": string;
    "model": string;
    "cores": number;
    "physmem": number;
    "uptime": string;
    "uptimeSeconds": number;
}

export interface SystemManagementOverview {
    "system": SystemInfo;
    "state": string;
    "services": SystemServiceInfo[] | null;
    "update": UpdateInfo;
}

export interface SystemServiceInfo {
    "id": number;
    "name": string;
    "state": string;
    "enabled": boolean;
}

export interface UpdateInfo {
    "status": string;
    "available": boolean;
    "version": string;
}

export interface UserInfo {
    "id": number;
    "uid": number;
    "username": string;
    "fullName": string;
    "email": string;
    "home": string;
    "shell": string;
    "local": boolean;
    "builtin": boolean;
    "immutable": boolean;
    "locked": boolean;
    "passwordDisabled": boolean;
    "sshPasswordEnabled": boolean;
    "sshPublicKey": string;
    "smb": boolean;
    "usernsIdmap": string;
    "primaryGroupId": number;
    "groups": number[] | null;
    "sudoCommands": string[] | null;
    "sudoCommandsNoPassword": string[] | null;
}

export interface UserMutation {
    "id": number;
    "uid": number;
    "setUid": boolean;
    "username": string;
    "fullName": string;
    "email": string;
    "home": string;
    "shell": string;
    "password": string;
    "randomPassword": boolean;
    "smb": boolean;
    "locked": boolean;
    "passwordDisabled": boolean;
    "sshPasswordEnabled": boolean;
    "sshPublicKey": string;
    "groupCreate": boolean;
    "primaryGroupId": number;
    "groups": number[] | null;
    "homeCreate": boolean;
    "homeMode": string;
    "usernsIdmap": string;
    "sudoCommands": string[] | null;
    "sudoCommandsNoPassword": string[] | null;
}

export interface UserMutationResult {
    "id": number;
    "password": string;
}
