// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrueNASService is the Wails backend boundary for TrueNAS API operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ACLTemplates(path: string): $CancellablePromise<$models.ACLTemplateInfo[] | null> {
    return $Call.ByID(242639040, path);
}

export function AppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(2980107274);
}

/**
 * CertificateOverview returns every certificate and which one the UI uses.
 */
export function CertificateOverview(): $CancellablePromise<$models.CertificateOverview> {
    return $Call.ByID(1220255893);
}

export function CheckinNetworkChanges(): $CancellablePromise<void> {
    return $Call.ByID(1074762265);
}

export function CommitNetworkChanges(checkinTimeout: number): $CancellablePromise<void> {
    return $Call.ByID(1149280317, checkinTimeout);
}

/**
 * Connect authenticates to TrueNAS, verifies the session with system.info,
 * then keeps the connection for subsequent service calls.
 */
export function Connect(endpoint: string, username: string, secret: string, authenticationMethod: string, allowPrivateCertificate: boolean, saveServer: boolean, saveCredential: boolean): $CancellablePromise<$models.ConnectionInfo> {
    return $Call.ByID(612684507, endpoint, username, secret, authenticationMethod, allowPrivateCertificate, saveServer, saveCredential);
}

/**
 * ConnectSavedServer signs in with a credential read entirely in the Go
 * backend so a stored password or API key is never returned to the frontend.
 */
export function ConnectSavedServer(id: string): $CancellablePromise<$models.ConnectionInfo> {
    return $Call.ByID(1992081393, id);
}

export function ControlSystemService(name: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(1097167144, name, action);
}

export function CreateDatasetSnapshot(input: $models.DatasetSnapshotMutation): $CancellablePromise<void> {
    return $Call.ByID(1712693173, input);
}

/**
 * CurrentConnection returns the in-memory connection state without exposing
 * credentials.
 */
export function CurrentConnection(): $CancellablePromise<$models.ConnectionInfo> {
    return $Call.ByID(2902204992);
}

/**
 * DeleteCertificate removes a certificate that is not bound to the UI.
 */
export function DeleteCertificate(id: number): $CancellablePromise<void> {
    return $Call.ByID(3608995003, id);
}

export function DeleteDataset(input: $models.DatasetDeleteOptions): $CancellablePromise<void> {
    return $Call.ByID(1321560836, input);
}

export function DeleteIdentity(kind: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(2705484798, kind, id);
}

export function DeleteNetworkInterface(id: string): $CancellablePromise<void> {
    return $Call.ByID(2935730273, id);
}

export function DeleteRsyncTask(id: number): $CancellablePromise<void> {
    return $Call.ByID(253646008, id);
}

/**
 * DeleteSavedServer removes one connection profile. It does not disconnect an
 * active session because saved profiles and live connections are independent.
 */
export function DeleteSavedServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3204391476, id);
}

export function DeleteShare(protocol: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(1024823263, protocol, id);
}

export function DeleteStaticRoute(id: number): $CancellablePromise<void> {
    return $Call.ByID(2599984891, id);
}

/**
 * Disconnect closes and clears the current TrueNAS connection.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(2224169341);
}

/**
 * GenerateSelfSignedCertificate produces a SAN certificate and key without
 * requiring OpenSSL on the workstation. It does not need a TrueNAS connection.
 */
export function GenerateSelfSignedCertificate(input: $models.SelfSignedCertificateRequest): $CancellablePromise<$models.GeneratedCertificate> {
    return $Call.ByID(571164929, input);
}

/**
 * GetFilesystemACL returns the resolved ACL for a dataset mount path.
 */
export function GetFilesystemACL(path: string): $CancellablePromise<$models.FilesystemACL> {
    return $Call.ByID(589481466, path);
}

export function GetSMBShareACL(shareName: string): $CancellablePromise<$models.SMBShareACL> {
    return $Call.ByID(1776517376, shareName);
}

export function IdentityOverview(): $CancellablePromise<$models.IdentityOverview> {
    return $Call.ByID(2813792206);
}

/**
 * InstallCertificate imports a PEM certificate and private key into TrueNAS
 * (Credentials > Certificates > Import) and, when requested, selects it as the
 * GUI SSL certificate and restarts the web service.
 */
export function InstallCertificate(input: $models.CertificateInstall): $CancellablePromise<number> {
    return $Call.ByID(4228500809, input);
}

/**
 * NetworkOverview returns the active network configuration together with any
 * staged interface changes waiting to be committed or checked in.
 */
export function NetworkOverview(): $CancellablePromise<$models.NetworkOverview> {
    return $Call.ByID(3743006440);
}

export function PowerAction(action: string): $CancellablePromise<void> {
    return $Call.ByID(3914884562, action);
}

export function RollbackNetworkChanges(): $CancellablePromise<void> {
    return $Call.ByID(3556726372);
}

export function RunRsyncTask(id: number): $CancellablePromise<void> {
    return $Call.ByID(733435212, id);
}

export function SaveAPIKey(input: $models.APIKeyMutation): $CancellablePromise<$models.APIKeyMutationResult> {
    return $Call.ByID(1017334685, input);
}

/**
 * SaveCertificateFiles asks for a destination via the native save dialog and
 * writes <name>.crt, <name>.key and san.cnf side by side. It returns the
 * directory that received the files, or "" when the user cancelled.
 */
export function SaveCertificateFiles(cert: $models.GeneratedCertificate): $CancellablePromise<string> {
    return $Call.ByID(816863368, cert);
}

/**
 * SaveDataset creates or updates a dataset. A changed ID is renamed only when
 * ForceRename is explicitly set because TrueNAS does not perform usage checks.
 */
export function SaveDataset(input: $models.DatasetMutation): $CancellablePromise<void> {
    return $Call.ByID(610650050, input);
}

export function SaveFilesystemACL(input: $models.FilesystemACLMutation): $CancellablePromise<void> {
    return $Call.ByID(1266504411, input);
}

export function SaveGroup(input: $models.GroupMutation): $CancellablePromise<void> {
    return $Call.ByID(2192222517, input);
}

export function SaveNetworkConfiguration(input: $models.NetworkConfigurationMutation): $CancellablePromise<void> {
    return $Call.ByID(999011698, input);
}

export function SaveNetworkInterface(input: $models.NetworkInterfaceMutation): $CancellablePromise<void> {
    return $Call.ByID(1019354723, input);
}

export function SaveRsyncTask(input: $models.RsyncTaskMutation): $CancellablePromise<void> {
    return $Call.ByID(1760596666, input);
}

export function SaveSMBShareACL(input: $models.SMBShareACL): $CancellablePromise<void> {
    return $Call.ByID(3552956521, input);
}

export function SaveShare(input: $models.ShareMutation): $CancellablePromise<void> {
    return $Call.ByID(1816958201, input);
}

export function SaveStaticRoute(input: $models.StaticRouteMutation): $CancellablePromise<void> {
    return $Call.ByID(1196458509, input);
}

export function SaveUser(input: $models.UserMutation): $CancellablePromise<$models.UserMutationResult> {
    return $Call.ByID(381118085, input);
}

/**
 * SavedServers returns connection profiles without exposing credentials.
 */
export function SavedServers(): $CancellablePromise<$models.SavedServer[] | null> {
    return $Call.ByID(1621806626);
}

/**
 * SelfSignedCertificateDefaults pre-fills the request from the current
 * connection so the user only has to confirm the hosts they reach TrueNAS by.
 */
export function SelfSignedCertificateDefaults(): $CancellablePromise<$models.SelfSignedCertificateRequest> {
    return $Call.ByID(16926974);
}

export function SetDatasetLocked(id: string, secret: string, lock: boolean, recursive: boolean, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(1344414149, id, secret, lock, recursive, force);
}

export function SetShareEnabled(protocol: string, id: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3485979745, protocol, id, enabled);
}

/**
 * SetUICertificate binds an existing certificate to the web GUI.
 */
export function SetUICertificate(id: number): $CancellablePromise<void> {
    return $Call.ByID(1147119378, id);
}

/**
 * SharingOverview returns SMB, NFS and rsync definitions.
 */
export function SharingOverview(): $CancellablePromise<$models.SharingOverview> {
    return $Call.ByID(975091646);
}

/**
 * StorageOverview fetches the storage collections in parallel at the Wails
 * boundary. A failure in any collection fails the refresh so stale partial
 * state is never presented as current.
 */
export function StorageOverview(): $CancellablePromise<$models.StorageOverview> {
    return $Call.ByID(360298927);
}

export function SystemManagementOverview(): $CancellablePromise<$models.SystemManagementOverview> {
    return $Call.ByID(3150336706);
}
