// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrueNASService is the Wails backend boundary for TrueNAS API operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(2980107274);
}

export function CheckinNetworkChanges(): $CancellablePromise<void> {
    return $Call.ByID(1074762265);
}

export function CommitNetworkChanges(checkinTimeout: number): $CancellablePromise<void> {
    return $Call.ByID(1149280317, checkinTimeout);
}

/**
 * Connect authenticates to TrueNAS, verifies the session with system.info,
 * then keeps the connection for subsequent service calls.
 */
export function Connect(endpoint: string, username: string, secret: string, authenticationMethod: string, allowPrivateCertificate: boolean, saveServer: boolean, saveCredential: boolean): $CancellablePromise<$models.ConnectionInfo> {
    return $Call.ByID(612684507, endpoint, username, secret, authenticationMethod, allowPrivateCertificate, saveServer, saveCredential);
}

/**
 * ConnectSavedServer signs in with a credential read entirely in the Go
 * backend so a stored password or API key is never returned to the frontend.
 */
export function ConnectSavedServer(id: string): $CancellablePromise<$models.ConnectionInfo> {
    return $Call.ByID(1992081393, id);
}

export function ControlSystemService(name: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(1097167144, name, action);
}

/**
 * CurrentConnection returns the in-memory connection state without exposing
 * credentials.
 */
export function CurrentConnection(): $CancellablePromise<$models.ConnectionInfo> {
    return $Call.ByID(2902204992);
}

export function DeleteIdentity(kind: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(2705484798, kind, id);
}

export function DeleteNetworkInterface(id: string): $CancellablePromise<void> {
    return $Call.ByID(2935730273, id);
}

/**
 * DeleteSavedServer removes one connection profile. It does not disconnect an
 * active session because saved profiles and live connections are independent.
 */
export function DeleteSavedServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3204391476, id);
}

export function DeleteShare(protocol: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(1024823263, protocol, id);
}

export function DeleteStaticRoute(id: number): $CancellablePromise<void> {
    return $Call.ByID(2599984891, id);
}

/**
 * Disconnect closes and clears the current TrueNAS connection.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(2224169341);
}

export function IdentityOverview(): $CancellablePromise<$models.IdentityOverview> {
    return $Call.ByID(2813792206);
}

/**
 * NetworkOverview returns the active network configuration together with any
 * staged interface changes waiting to be committed or checked in.
 */
export function NetworkOverview(): $CancellablePromise<$models.NetworkOverview> {
    return $Call.ByID(3743006440);
}

export function PowerAction(action: string): $CancellablePromise<void> {
    return $Call.ByID(3914884562, action);
}

export function RollbackNetworkChanges(): $CancellablePromise<void> {
    return $Call.ByID(3556726372);
}

export function RunRsyncTask(id: number): $CancellablePromise<void> {
    return $Call.ByID(733435212, id);
}

export function SaveAPIKey(input: $models.APIKeyMutation): $CancellablePromise<$models.APIKeyMutationResult> {
    return $Call.ByID(1017334685, input);
}

export function SaveGroup(input: $models.GroupMutation): $CancellablePromise<void> {
    return $Call.ByID(2192222517, input);
}

export function SaveNetworkConfiguration(input: $models.NetworkConfigurationMutation): $CancellablePromise<void> {
    return $Call.ByID(999011698, input);
}

export function SaveNetworkInterface(input: $models.NetworkInterfaceMutation): $CancellablePromise<void> {
    return $Call.ByID(1019354723, input);
}

export function SaveRsyncTask(input: $models.RsyncTaskMutation): $CancellablePromise<void> {
    return $Call.ByID(1760596666, input);
}

export function SaveShare(input: $models.ShareMutation): $CancellablePromise<void> {
    return $Call.ByID(1816958201, input);
}

export function SaveStaticRoute(input: $models.StaticRouteMutation): $CancellablePromise<void> {
    return $Call.ByID(1196458509, input);
}

export function SaveUser(input: $models.UserMutation): $CancellablePromise<$models.UserMutationResult> {
    return $Call.ByID(381118085, input);
}

/**
 * SavedServers returns connection profiles without exposing credentials.
 */
export function SavedServers(): $CancellablePromise<$models.SavedServer[] | null> {
    return $Call.ByID(1621806626);
}

export function SetShareEnabled(protocol: string, id: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3485979745, protocol, id, enabled);
}

/**
 * SharingOverview returns SMB, NFS and rsync definitions.
 */
export function SharingOverview(): $CancellablePromise<$models.SharingOverview> {
    return $Call.ByID(975091646);
}

/**
 * StorageOverview fetches the storage collections in parallel at the Wails
 * boundary. A failure in any collection fails the refresh so stale partial
 * state is never presented as current.
 */
export function StorageOverview(): $CancellablePromise<$models.StorageOverview> {
    return $Call.ByID(360298927);
}

export function SystemManagementOverview(): $CancellablePromise<$models.SystemManagementOverview> {
    return $Call.ByID(3150336706);
}
