// Code generated by cmd/genstorage from TrueNAS API v25.10.5; DO NOT EDIT.
package truenas

import (
	"context"
	"encoding/json"
)

type StorageMethod struct {
	Name, Service, Kind string
	Destructive         bool
}

var StorageMethods = [...]StorageMethod{
	{Name: "device.get_info", Service: "DeviceService", Kind: "read", Destructive: false},
	{Name: "disk.details", Service: "DiskService", Kind: "read", Destructive: false},
	{Name: "disk.get_used", Service: "DiskService", Kind: "change", Destructive: false},
	{Name: "disk.query", Service: "DiskService", Kind: "read", Destructive: false},
	{Name: "disk.temperature_agg", Service: "DiskService", Kind: "change", Destructive: false},
	{Name: "disk.temperature_alerts", Service: "DiskService", Kind: "change", Destructive: false},
	{Name: "disk.temperatures", Service: "DiskService", Kind: "change", Destructive: false},
	{Name: "disk.update", Service: "DiskService", Kind: "change", Destructive: false},
	{Name: "disk.wipe", Service: "DiskService", Kind: "destructive", Destructive: true},
	{Name: "enclosure.label.set", Service: "EnclosureService", Kind: "change", Destructive: false},
	{Name: "enclosure2.query", Service: "EnclosureService", Kind: "read", Destructive: false},
	{Name: "enclosure2.set_slot_status", Service: "EnclosureService", Kind: "change", Destructive: false},
	{Name: "filesystem.acltemplate.by_path", Service: "ACLTemplateService", Kind: "change", Destructive: false},
	{Name: "filesystem.acltemplate.create", Service: "ACLTemplateService", Kind: "create", Destructive: false},
	{Name: "filesystem.acltemplate.delete", Service: "ACLTemplateService", Kind: "destructive", Destructive: true},
	{Name: "filesystem.acltemplate.get_instance", Service: "ACLTemplateService", Kind: "read", Destructive: false},
	{Name: "filesystem.acltemplate.query", Service: "ACLTemplateService", Kind: "read", Destructive: false},
	{Name: "filesystem.acltemplate.update", Service: "ACLTemplateService", Kind: "change", Destructive: false},
	{Name: "filesystem.chown", Service: "FilesystemService", Kind: "change", Destructive: true},
	{Name: "filesystem.get", Service: "FilesystemService", Kind: "change", Destructive: false},
	{Name: "filesystem.get_zfs_attributes", Service: "FilesystemService", Kind: "change", Destructive: false},
	{Name: "filesystem.getacl", Service: "FilesystemService", Kind: "read", Destructive: false},
	{Name: "filesystem.listdir", Service: "FilesystemService", Kind: "read", Destructive: false},
	{Name: "filesystem.mkdir", Service: "FilesystemService", Kind: "create", Destructive: false},
	{Name: "filesystem.put", Service: "FilesystemService", Kind: "change", Destructive: false},
	{Name: "filesystem.set_zfs_attributes", Service: "FilesystemService", Kind: "change", Destructive: false},
	{Name: "filesystem.setacl", Service: "FilesystemService", Kind: "change", Destructive: true},
	{Name: "filesystem.setperm", Service: "FilesystemService", Kind: "change", Destructive: true},
	{Name: "filesystem.stat", Service: "FilesystemService", Kind: "read", Destructive: false},
	{Name: "filesystem.statfs", Service: "FilesystemService", Kind: "read", Destructive: false},
	{Name: "pool.attach", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.attachments", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.create", Service: "PoolService", Kind: "create", Destructive: false},
	{Name: "pool.dataset.attachments", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.change_key", Service: "DatasetService", Kind: "change", Destructive: true},
	{Name: "pool.dataset.checksum_choices", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.compression_choices", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.create", Service: "DatasetService", Kind: "create", Destructive: false},
	{Name: "pool.dataset.delete", Service: "DatasetService", Kind: "destructive", Destructive: true},
	{Name: "pool.dataset.details", Service: "DatasetService", Kind: "read", Destructive: false},
	{Name: "pool.dataset.encryption_summary", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.export_key", Service: "DatasetService", Kind: "change", Destructive: true},
	{Name: "pool.dataset.export_keys", Service: "DatasetService", Kind: "change", Destructive: true},
	{Name: "pool.dataset.export_keys_for_replication", Service: "DatasetService", Kind: "change", Destructive: true},
	{Name: "pool.dataset.get_instance", Service: "DatasetService", Kind: "read", Destructive: false},
	{Name: "pool.dataset.get_quota", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.inherit_parent_encryption_properties", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.lock", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.processes", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.promote", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.query", Service: "DatasetService", Kind: "read", Destructive: false},
	{Name: "pool.dataset.recommended_zvol_blocksize", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.recordsize_choices", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.rename", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.set_quota", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.snapshot_count", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.unlock", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.dataset.update", Service: "DatasetService", Kind: "change", Destructive: false},
	{Name: "pool.ddt_prefetch", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.ddt_prune", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.detach", Service: "PoolService", Kind: "destructive", Destructive: true},
	{Name: "pool.expand", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.export", Service: "PoolService", Kind: "destructive", Destructive: true},
	{Name: "pool.filesystem_choices", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.get_disks", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.get_instance", Service: "PoolService", Kind: "read", Destructive: false},
	{Name: "pool.import_find", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.import_pool", Service: "PoolService", Kind: "create", Destructive: false},
	{Name: "pool.is_upgraded", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.offline", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.online", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.processes", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.query", Service: "PoolService", Kind: "read", Destructive: false},
	{Name: "pool.remove", Service: "PoolService", Kind: "destructive", Destructive: true},
	{Name: "pool.replace", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.resilver.config", Service: "ResilverService", Kind: "read", Destructive: false},
	{Name: "pool.resilver.update", Service: "ResilverService", Kind: "change", Destructive: false},
	{Name: "pool.scrub.create", Service: "ScrubService", Kind: "create", Destructive: false},
	{Name: "pool.scrub.delete", Service: "ScrubService", Kind: "destructive", Destructive: true},
	{Name: "pool.scrub.get_instance", Service: "ScrubService", Kind: "read", Destructive: false},
	{Name: "pool.scrub.query", Service: "ScrubService", Kind: "read", Destructive: false},
	{Name: "pool.scrub.run", Service: "ScrubService", Kind: "change", Destructive: false},
	{Name: "pool.scrub.scrub", Service: "ScrubService", Kind: "change", Destructive: false},
	{Name: "pool.scrub.update", Service: "ScrubService", Kind: "change", Destructive: false},
	{Name: "pool.snapshot.clone", Service: "SnapshotService", Kind: "create", Destructive: false},
	{Name: "pool.snapshot.create", Service: "SnapshotService", Kind: "create", Destructive: false},
	{Name: "pool.snapshot.delete", Service: "SnapshotService", Kind: "destructive", Destructive: true},
	{Name: "pool.snapshot.get_instance", Service: "SnapshotService", Kind: "read", Destructive: false},
	{Name: "pool.snapshot.hold", Service: "SnapshotService", Kind: "change", Destructive: false},
	{Name: "pool.snapshot.query", Service: "SnapshotService", Kind: "read", Destructive: false},
	{Name: "pool.snapshot.release", Service: "SnapshotService", Kind: "change", Destructive: false},
	{Name: "pool.snapshot.rename", Service: "SnapshotService", Kind: "change", Destructive: false},
	{Name: "pool.snapshot.rollback", Service: "SnapshotService", Kind: "destructive", Destructive: true},
	{Name: "pool.snapshot.update", Service: "SnapshotService", Kind: "change", Destructive: false},
	{Name: "pool.snapshottask.create", Service: "SnapshotTaskService", Kind: "create", Destructive: false},
	{Name: "pool.snapshottask.delete", Service: "SnapshotTaskService", Kind: "destructive", Destructive: true},
	{Name: "pool.snapshottask.delete_will_change_retention_for", Service: "SnapshotTaskService", Kind: "change", Destructive: true},
	{Name: "pool.snapshottask.get_instance", Service: "SnapshotTaskService", Kind: "read", Destructive: false},
	{Name: "pool.snapshottask.max_count", Service: "SnapshotTaskService", Kind: "change", Destructive: false},
	{Name: "pool.snapshottask.max_total_count", Service: "SnapshotTaskService", Kind: "change", Destructive: false},
	{Name: "pool.snapshottask.query", Service: "SnapshotTaskService", Kind: "read", Destructive: false},
	{Name: "pool.snapshottask.run", Service: "SnapshotTaskService", Kind: "change", Destructive: false},
	{Name: "pool.snapshottask.update", Service: "SnapshotTaskService", Kind: "change", Destructive: false},
	{Name: "pool.snapshottask.update_will_change_retention_for", Service: "SnapshotTaskService", Kind: "change", Destructive: false},
	{Name: "pool.update", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.upgrade", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "pool.validate_name", Service: "PoolService", Kind: "change", Destructive: false},
	{Name: "zfs.resource.query", Service: "ZFSResourceService", Kind: "read", Destructive: false},
}

func StorageMethodByName(name string) (StorageMethod, bool) {
	for _, m := range StorageMethods {
		if m.Name == name {
			return m, true
		}
	}
	return StorageMethod{}, false
}
func (s DeviceService) GetInfo(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_info", r)
}
func (s DiskService) Details(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "details", r)
}
func (s DiskService) GetUsed(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_used", r)
}
func (s DiskService) Query(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "query", r)
}
func (s DiskService) TemperatureAgg(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "temperature_agg", r)
}
func (s DiskService) TemperatureAlerts(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "temperature_alerts", r)
}
func (s DiskService) Temperatures(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "temperatures", r)
}
func (s DiskService) Update(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "update", r)
}
func (s DiskService) Wipe(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "wipe", r)
}
func (s EnclosureService) Set(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "label.set", r)
}
func (s EnclosureService) Query(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "query", r)
}
func (s EnclosureService) SetSlotStatus(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "set_slot_status", r)
}
func (s ACLTemplateService) ByPath(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "by_path", r)
}
func (s ACLTemplateService) Create(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "create", r)
}
func (s ACLTemplateService) Delete(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "delete", r)
}
func (s ACLTemplateService) GetInstance(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_instance", r)
}
func (s ACLTemplateService) Query(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "query", r)
}
func (s ACLTemplateService) Update(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "update", r)
}
func (s FilesystemService) Chown(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "chown", r)
}
func (s FilesystemService) Get(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get", r)
}
func (s FilesystemService) GetZfsAttributes(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_zfs_attributes", r)
}
func (s FilesystemService) Getacl(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "getacl", r)
}
func (s FilesystemService) Listdir(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "listdir", r)
}
func (s FilesystemService) Mkdir(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "mkdir", r)
}
func (s FilesystemService) Put(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "put", r)
}
func (s FilesystemService) SetZfsAttributes(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "set_zfs_attributes", r)
}
func (s FilesystemService) Setacl(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "setacl", r)
}
func (s FilesystemService) Setperm(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "setperm", r)
}
func (s FilesystemService) Stat(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "stat", r)
}
func (s FilesystemService) Statfs(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "statfs", r)
}
func (s PoolService) Attach(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "attach", r)
}
func (s PoolService) Attachments(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "attachments", r)
}
func (s PoolService) Create(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "create", r)
}
func (s DatasetService) Attachments(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "attachments", r)
}
func (s DatasetService) ChangeKey(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "change_key", r)
}
func (s DatasetService) ChecksumChoices(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "checksum_choices", r)
}
func (s DatasetService) CompressionChoices(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "compression_choices", r)
}
func (s DatasetService) Create(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "create", r)
}
func (s DatasetService) Delete(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "delete", r)
}
func (s DatasetService) Details(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "details", r)
}
func (s DatasetService) EncryptionSummary(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "encryption_summary", r)
}
func (s DatasetService) ExportKey(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "export_key", r)
}
func (s DatasetService) ExportKeys(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "export_keys", r)
}
func (s DatasetService) ExportKeysForReplication(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "export_keys_for_replication", r)
}
func (s DatasetService) GetInstance(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_instance", r)
}
func (s DatasetService) GetQuota(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_quota", r)
}
func (s DatasetService) InheritParentEncryptionProperties(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "inherit_parent_encryption_properties", r)
}
func (s DatasetService) Lock(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "lock", r)
}
func (s DatasetService) Processes(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "processes", r)
}
func (s DatasetService) Promote(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "promote", r)
}
func (s DatasetService) Query(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "query", r)
}
func (s DatasetService) RecommendedZvolBlocksize(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "recommended_zvol_blocksize", r)
}
func (s DatasetService) RecordsizeChoices(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "recordsize_choices", r)
}
func (s DatasetService) Rename(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "rename", r)
}
func (s DatasetService) SetQuota(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "set_quota", r)
}
func (s DatasetService) SnapshotCount(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "snapshot_count", r)
}
func (s DatasetService) Unlock(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "unlock", r)
}
func (s DatasetService) Update(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "update", r)
}
func (s PoolService) DdtPrefetch(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "ddt_prefetch", r)
}
func (s PoolService) DdtPrune(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "ddt_prune", r)
}
func (s PoolService) Detach(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "detach", r)
}
func (s PoolService) Expand(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "expand", r)
}
func (s PoolService) Export(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "export", r)
}
func (s PoolService) FilesystemChoices(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "filesystem_choices", r)
}
func (s PoolService) GetDisks(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_disks", r)
}
func (s PoolService) GetInstance(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_instance", r)
}
func (s PoolService) ImportFind(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "import_find", r)
}
func (s PoolService) ImportPool(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "import_pool", r)
}
func (s PoolService) IsUpgraded(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "is_upgraded", r)
}
func (s PoolService) Offline(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "offline", r)
}
func (s PoolService) Online(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "online", r)
}
func (s PoolService) Processes(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "processes", r)
}
func (s PoolService) Query(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "query", r)
}
func (s PoolService) Remove(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "remove", r)
}
func (s PoolService) Replace(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "replace", r)
}
func (s ResilverService) Config(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "config", r)
}
func (s ResilverService) Update(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "update", r)
}
func (s ScrubService) Create(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "create", r)
}
func (s ScrubService) Delete(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "delete", r)
}
func (s ScrubService) GetInstance(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_instance", r)
}
func (s ScrubService) Query(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "query", r)
}
func (s ScrubService) Run(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "run", r)
}
func (s ScrubService) Scrub(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "scrub", r)
}
func (s ScrubService) Update(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "update", r)
}
func (s SnapshotService) Clone(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "clone", r)
}
func (s SnapshotService) Create(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "create", r)
}
func (s SnapshotService) Delete(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "delete", r)
}
func (s SnapshotService) GetInstance(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_instance", r)
}
func (s SnapshotService) Hold(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "hold", r)
}
func (s SnapshotService) Query(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "query", r)
}
func (s SnapshotService) Release(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "release", r)
}
func (s SnapshotService) Rename(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "rename", r)
}
func (s SnapshotService) Rollback(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "rollback", r)
}
func (s SnapshotService) Update(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "update", r)
}
func (s SnapshotTaskService) Create(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "create", r)
}
func (s SnapshotTaskService) Delete(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "delete", r)
}
func (s SnapshotTaskService) DeleteWillChangeRetentionFor(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "delete_will_change_retention_for", r)
}
func (s SnapshotTaskService) GetInstance(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "get_instance", r)
}
func (s SnapshotTaskService) MaxCount(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "max_count", r)
}
func (s SnapshotTaskService) MaxTotalCount(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "max_total_count", r)
}
func (s SnapshotTaskService) Query(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "query", r)
}
func (s SnapshotTaskService) Run(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "run", r)
}
func (s SnapshotTaskService) Update(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "update", r)
}
func (s SnapshotTaskService) UpdateWillChangeRetentionFor(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "update_will_change_retention_for", r)
}
func (s PoolService) Update(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "update", r)
}
func (s PoolService) Upgrade(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "upgrade", r)
}
func (s PoolService) ValidateName(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "validate_name", r)
}
func (s ZFSResourceService) Query(ctx context.Context, r StorageCall) (json.RawMessage, error) {
	return s.Call(ctx, "query", r)
}
